namespace SmartCampusServicesPortal.Data.Enums;

public enum UserAction
{
    Login = 1,
    UpdateProfile = 2,
    ViewTimetable = 3,
    AssignClassSchedule = 4,
    UpdateClassSchedule = 5,
    DeleteClassSchedule = 6,
    ViewAvailableRooms = 7,
    BookRoom = 8,
    CancelRoomBooking = 9,
    ViewMyBookings = 10,
    ApproveBooking = 11,
    RejectBooking = 12,
    ReportMaintenanceIssue = 13,
    UpdateMaintenanceIssue = 14,
    CloseMaintenanceIssue = 15,
    ViewMaintenanceRequests = 16,
    AssignMaintenanceIssue = 17,
    SendSubjectNotification = 18,
    SendGeneralNotification = 19,
    ViewNotifications = 20,
    DeleteAnnouncement = 21,
    MarkNotificationAsRead = 22,
    ViewStudentSubjectEnrollments = 23,
    ExportTimetableAsPdf = 24,
    ViewLogs = 25,
    RevokeActionFromGroup = 26,
    AssignActionToGroup = 27,
    RemoveUserFromGroup = 28,
    AddUserToGroup = 29,
    DeleteGroup = 30,
    UpdateGroup = 31,
    CreateGroup = 32,
    UnlockUser = 33,
    AddGroupAction = 34,
    DeleteGroupAction = 35,
    DeleteGroupMember = 36,
    SetGroupMember = 37,
    ResetPassword = 38,
    ChangePassword = 39,
    LockUser = 40,
    StudentEnrollmentSubject = 41,
    ViewProfile = 42
}